### ISSUE TITLE
Keyboard on screen - no input

### ISSUE THREAD

**Issue by Kempes7475** [Cathwyler/MagicRemoteService#10]
First of all thank you for great job! Today I managed to set it on LG 43UK6470 WebOS 4.4 and Windows 11 Pro. It works! But... blue button pops-up on screen LG keyboard but I can't write/input any text. It just does not work. Red button allows me to shutdown (not sleep) my PC so I'm not able to wake up Windows but even when PC goes asleep (or I force sleep mode in power menu) I can not  wake it. When I choose MagicRemoteService in TV source menu I have option to push button Start to wake up but there is message that Wake on Lan doesn't work. (I tried also red button). Wake on Lan is set up because I'm able to wake up PC via android phone or chromebook. PC MAC address is correct in MagicRemoteService app so I dont know why it doesn't work.
Thank you in advance for support regarding keyboard and wake on lan issues.

**Comment by Cathwyler** [comment]
Hi,

Sorry for not answering you earlier.

About the keyboard not working, i don't have actually any possibilty to test on windows 11. Do you use Latin characters or any unicode alphabet ?

About the Wake-on-LAN can you try use [Wireshark](https://www.wireshark.org/download.html) and tell me if you properly receive or not the Wake-on-LAN message ? Unplug the HDMI and the TV will think the PC is shut down and you will have access to the startup button. After strike the button, the TV is broadcasting the magic packet every 5 seconds.
You will be able to compare and see if there is any difference betwen the magic packet sent by your chromebook or your android phone and the TV.

Which android app are you using ?

**Comment by Kempes7475** [comment]
> Hi,
> 
> Sorry for not answering you earlier.
> 
> About the keyboard not working, i don't have actually any possibilty to test on windows 11. Do you use Latin characters or any unicode alphabet ?
> 
> About the Wake-on-LAN can you try use [Wireshark](https://www.wireshark.org/download.html) and tell me if you properly receive or not the Wake-on-LAN message ? Unplug the HDMI and the TV will think the PC is shut down and you will have access to the startup button. After strike the button, the TV is broadcasting the magic packet every 5 seconds.
> You will be able to compare and see if there is any difference betwen the magic packet sent by your chromebook or your android phone and the TV.
> 
> Which android app are you using ?
> 
> 
> 

Hi

Thanks for reply! I just installed 1.2.2.3 so I'm updated. So, I use polish language in Windows and on TV. After your comment I changed in Windows into English US and also keyboard layout English US. After pressing blue button I swap also LG TV keyboard from POL to ENG. Now I think that I should try maybe change also whole region on TV (from polish to english) I don't know...Regarding Windows 11 I have old laptop with Windows 10 so I'll try tomorrow and let you know result. Wireshark - I have to figure out how it works and I will make tests. To wake up my computers (2 PCs and 1 laptop) I use android Unified Remote Full version. As soon as I get test results I'll let you know.

**Comment by Kempes7475** [comment]
So yesterday finally I was able to connect my Win10 laptop and...keyboard works (wake-up don't). And today I noticed that there is new 1.2.2.5 version. And now HTPC Windows Win11 works also with bluekey keyboard!!! That's awsome!!! With polish language setting both on LG TV and Windows. Now I have to figure out this Wireshark and wake-up issue. Once again many thanks for your great job!
