### ISSUE TITLE
Multimedia Keys not assignable

### ISSUE THREAD

**Issue by Chron-O-John** [Cathwyler/MagicRemoteService#13]
When assigning a ney key to a button of the remote the programm does not react to "Multimedia Buttons" like the Play/Pause button. It would be nice to be able to bind these

**Comment by Cathwyler** [comment]
Unfortunately, media key is a hardware binding or work through driver level.

But for Play/Pause functionality you can use the space bar binding. It is working in most of case.

Regards

**Comment by Cathwyler** [comment]
Switched the keys binding from scan code to virtual code. https://github.com/Cathwyler/MagicRemoteService/releases/tag/1.2.2.9

Let me know if it work as intended.

**Comment by Chron-O-John** [comment]
Hi,
Could you please compile this release?
Thanks

**Comment by Chron-O-John** [comment]
Wanted to try it, but the latest release is missing the executable file.
Thanks

**Comment by Cathwyler** [comment]
Woops. I fixed the release
