### ISSUE TITLE
Suddenly stopped working?

### ISSUE THREAD

**Issue by gogosimba** [Cathwyler/MagicRemoteService#17]
When I try to launch the magicremoteservice from my lgsmarttv the icon is missing and it wont start anymore. What's really odd is that I haven't updated my os on the tv, any ideas?

**Comment by Cathwyler** [comment]
Hi,You probably reach the end of the developer mode time session that is 999h max. This is a LG limitation. You need to extend session time every month else you need reenable dev mode session and reinstall tv app. There is an old outdated option in the the pc app that extend session time automaticaly every day (The session time max was 99h in earlier webos version). Or you can use a scheduled task with ares-extend-dev (See readme). I will probably update this option soon to make it more convenient.Regards
-------- Message d'origine --------De : Jonathan Johansson ***@***.***> Date : 21/12/2023  15:11  (GMT+01:00) À : Cathwyler/MagicRemoteService ***@***.***> Cc : Subscribed ***@***.***> Objet : [Cathwyler/MagicRemoteService] Suddenly stopped working? (Issue #17) 
When I try to launch the magicremoteservice from my lgsmarttv the icon is missing and it wont start anymore. What's really odd is that I haven't updated my os on the tv, any ideas?
