### ISSUE TITLE
Bind a key to launch a program [enhancement]

### ISSUE THREAD

**Issue by Peskinator** [Cathwyler/MagicRemoteService#18]
Hello, 
Thank you so much for your effort. It's working really great.

I was wondering if it was possible to bind a key to launch a executable file. So far it seems I can only bind to a Key or a to Mouse action.
For instance, using programs like NirCmd will bring endless possibilities.

Thanks again!

**Comment by Cathwyler** [comment]
Hi, thanks for your feedback

I will add a cmd binding in a future version.

regards

**Comment by Peskinator** [comment]
Thank you very much :)

**Comment by Cathwyler** [comment]
You can try this pre-release [1.2.3.0](https://github.com/Cathwyler/MagicRemoteService/releases/tag/1.2.3.0). I added the possibility to set a command line on a remote bind.

Let me know if it works fine.

**Comment by Peskinator** [comment]
It works perfectly!
Thanks!!
Note that I had to restart the executable for the changes to take effect (which is totally fine for me)
