### ISSUE TITLE
Can't see TV

### ISSUE THREAD

**Issue by philcatterall** [Cathwyler/MagicRemoteService#2]
Hi Cathwyler,
This is a genius app, and thanks for putting it out there !!
I'm having a problem though. I've built it (VS2022), built and runs fine, but its not seeing my TV and I'm definitely on the same network.
Is there a way of specifying the TV IP address ?
I've got windows firewall off, so ports shouldn't be an isse.
Any help, gratefully received.
Cheers, Phil

**Comment by Cathwyler** [comment]
Hi philcatterall,

MagicRemoteService use official WebOS CLI to configure TV but it needs some tricky configuration at the beginning. The IP address of the TV is specified when you add your TV with WebOS CLI interface during the installation.
- First make sure you properly installed WebOS CLI on your PC. Please refer to https://webostv.developer.lge.com/develop/tools/cli-installation. If at start you don't have this error 

  With WebOS CLI not properly installed you should see an error message at start or when refreshing TV
![Error message](https://github.com/Cathwyler/MagicRemoteService/assets/4673422/66df56ba-8110-4b2a-bd02-d1651618ea7e)
And an empty TV list
![Empty TV list](https://github.com/Cathwyler/MagicRemoteService/assets/4673422/65e77666-d4a1-459f-b647-cf0754412356)

  With WebOS CLI properly installed you should see at least the emulator in the TV list
![Emulator in the TV list](https://github.com/Cathwyler/MagicRemoteService/assets/4673422/5140b5e6-f0e2-4741-b1be-b4e060739f27)

- Second make sure you properly installed and activated developer mode app on your LG WebOS TV and make sur you added your TV in the WebOS CLI . Please refer to https://webostv.developer.lge.com/develop/getting-started/developer-mode-app (Section "Installing Developer Mode app" and "Turning Developer Mode on").

- Third make sur you properly added your TV in your WebOS CLI. Please refer to https://webostv.developer.lge.com/develop/getting-started/developer-mode-app (Section "Connecting TV and PC -> Connecting with CLI").

  With TVs properly added in WebOS CLI
![TVs properly added in WebOS CLI](https://github.com/Cathwyler/MagicRemoteService/assets/4673422/75a1070f-8514-4a73-8fa8-7d68733a3cea)

I hope you will find these explanations useful.
Feel free to contact me again in case of issues.

Regards,

Cathwyler

**Comment by Cathwyler** [comment]
Hi,

You can now manage your TVs inside the PC app in this new release [1.2.1.0](https://github.com/Cathwyler/MagicRemoteService/releases/tag/1.2.1.0)

Regards,

Cathwyler
