### ISSUE TITLE
0-9 key binding, Swapped Middle and Right button

### ISSUE THREAD

**Issue by EinarVaagland** [Cathwyler/MagicRemoteService#22]
Wonderful tool! I've been looking for this since I tried a Magic Remote several years ago, and why LG won't make a USB receiver is beyond me, the accuracy of the mouse is the best I've found. And your implementation is genious, please make a Patreon so we can help fund this project. 

If I can make a wish, I'd want to assign actions to all the buttons, using 0-9 to run programs for example.

I've found an error. When assigning the Middle click to a colored button, the Right click is selected and vice versa.

BindCreator.cs:

```
private void MouseLeft_CheckedChanged(object sender, System.EventArgs e) {
  if(((System.Windows.Forms.RadioButton)sender).Checked) {
    this.arrBind = new Bind[] { new MagicRemoteService.BindMouse(BindMouseValue.Left) }; //Left
  }
}
private void MouseMiddle_CheckedChanged(object sender, System.EventArgs e) {
  if(((System.Windows.Forms.RadioButton)sender).Checked) {
    this.arrBind = new Bind[] { new MagicRemoteService.BindMouse(BindMouseValue.Right) }; //Middle
  }
}
private void MouseRight_CheckedChanged(object sender, System.EventArgs e) {
  if(((System.Windows.Forms.RadioButton)sender).Checked) {
    this.arrBind = new Bind[] { new MagicRemoteService.BindMouse(BindMouseValue.Middle) }; //Right
  }
}

```

**Comment by Cathwyler** [comment]
Hi,

Thanks for your feedback.

I fixed the swapped middle and right click. It will be available in the next release.

About 0-9 key binding I will look further if there is a way to subscribe these events.

**Comment by Cathwyler** [comment]
Hi,

I added 0-9 keybindon the latest release.

Regards

**Comment by Einar-Vaagland** [comment]
Thank you!
