### ISSUE TITLE
MAP BUTTON

### ISSUE THREAD

**Issue by dellas60** [Cathwyler/MagicRemoteService#25]
I WANT TO THANK YOU FOR THIS EXCELLENT TOOL. 
SECONDLY CAN I MAP THE PROGRAM UP AND DOWN AND VOLUM UP AND DOWN BUTTONS. 
THIRDLY YOU MENTIONS  THE BUTTONS THAT ARE NOT AVAILABLE IN REMOTE EXAMPLE AVANCE RAPID AND REMBOBINE WHY?

**Comment by Cathwyler** [comment]
Thanks for your feedback.

I will take a look if it's possible to get program and volume event from web app but in my opinion they are not triggered.
The media button are available on the old remote control model.

Regards

**Comment by dellas60** [comment]
I tried to modify your code but I am stuck in the key code for channel up and down how you get code key for remote in officiel site there is only code for new remote and if i scan example red key iget 403 i have an mr 18 remote

**Comment by Cathwyler** [comment]
https://webostv.developer.lge.com/develop/guides/magic-remote
Unfortunatelly there is no more info from LG Official website.

**Comment by dellas60** [comment]
Can I use the code key scanned by this app https://github.com/webOS-TV-app-samples/RemoteControl?tab=readme-ov-file in your app

**Comment by Cathwyler** [comment]
If you find the keycode you can add a regkey in the registry there and restart the service withoot any code change.
HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\MagicRemoteService\Remote\Bind\[HEX_WEBOS_KEY_CODE]\0\

**Comment by Cathwyler** [comment]
Seems that program key are working on 0x0021 and 0x0022.
I will add them in a futur release.

Unfortunatly volume key are not triggering any event.
If you find a way i will add it too.

**Comment by dellas60** [comment]
I am very happy that you are doing a great job, can this help ?https://github.com/andrewfraley/magic_mapper/blob/main/magic_mapper.py

**Comment by dellas60** [comment]
Si possible, comment obtenir ces deux codes 0x0021 et 0x0022

**Comment by Cathwyler** [comment]
Hi,

I added channel +/- binding possibility in the latest release.

I will take a closer look on the magic_mapper source code but it seems this is available only for rooted TV.
MagicRemoteService is designed for non rooted TV. Unfortunatly i will not add rooted specific feature in this app.
If you find a rooted way by yourself feel free to post it there.

Regards
