### ISSUE TITLE
Using Magic Remote microphone as text input?

### ISSUE THREAD

**Issue by TehDomic** [Cathwyler/MagicRemoteService#29]
I have tried starting voice input from the WebOS keyboard, however, it only sends the first letter of the recorded words to the MagicRemoteService application when MRS is trying to send the speech-to-text output to Windows.

Would it be possible for the application to receive speech-to-text input when pressing the Mic button on the remote while the MRS application is active on the LG TV, instead of it activating a "Universal Voice Search" across all WebOS applications?

**Comment by Cathwyler** [comment]
I think i know why it send only the first letter.
I will take a look and try to fix this.
There is no reason the voice input does not work.

**Comment by Cathwyler** [comment]
It should be fixed in the latest release

**Comment by TehDomic** [comment]
Tested 1.2.4.7 today, sorry to report that my tests still only enters "1" when trying to send "12345" from WebOS. Same with saying words, sentences etc. :(

**Comment by Cathwyler** [comment]
Did you reinstall the app on TV ?
Can you send me your TV version ?

**Comment by TehDomic** [comment]
TV version
---------------------------
modelName : 70NANO756PA
sdkVersion : 6.3.2
firmwareVersion : 03.34.70
boardType : LM21A_DVB_EU
otaId : HE_DTV_W21A_AFADATAA

**Comment by TehDomic** [comment]
Uninstalling and installing the TV app manually seemed to fix it. Thanks. Works as intended :)
