### ISSUE TITLE
Error code when installing on TV

### ISSUE THREAD

**Issue by Spottyfriend** [Cathwyler/MagicRemoteService#3]
I've reached the step of installing onto the PC, and MagicRemoteService sees the TV I added (with the name I chose so it's definitely there), but I receive this error... I've double checked the IP, Subnet mask, and MAC address on my PC and they're all correct. Any help much appreciated!

![image](https://github.com/Cathwyler/MagicRemoteService/assets/50644325/62a97da0-a50c-43d3-94fd-5040f21d0df6)

**Comment by oliarn** [comment]
+1

Thanks in advance!

![image](https://github.com/Cathwyler/MagicRemoteService/assets/20297071/05914fc6-d9e0-437c-bf86-a2f33e2ce34f)

**Comment by Cathwyler** [comment]
Hi,

This error is a webOS CLI issue.

There is 2 thread about this issue on Lg community forum :
https://forum.webostv.developer.lge.com/t/ares-install-error-command/2465
https://forum.webostv.developer.lge.com/t/an-error-appears-when-im-trying-to-install-ipk-file/2345

Make sure you have "1.12.4-j27" CLI version installed. You can type "ares -V" in webOS CLI to know your version or in package.json in your LG_WEBOS_TV_SDK_HOME environement path.

Make sure you uninstalled webOS OSE CLI (@webosose/ares-cli) with npm if you had one installed.

Hope it will help.

**Comment by Spottyfriend** [comment]
Thanks - I think it was just the case of the wrong CLI version as you suggested.
