### ISSUE TITLE
System.Text.Json error

### ISSUE THREAD

**Issue by bturne48** [Cathwyler/MagicRemoteService#34]
Hello, recently updated to the latest tv os, now receiving this error. Any help?

![image](https://github.com/Cathwyler/MagicRemoteService/assets/47575552/2b4f66e0-6a66-4506-97db-8b5e1e3f1c9c)

**Comment by Cathwyler** [comment]
This is probably a Windows or antivirus issue.
You probably miss "System.Text.Json.dll" or "MagicRemoteService.exe.config" file next  to the "MagicRemoteService.exe".

Did you properly extracted the zip file ?
Make sure you don't have any instance of the service running in the background and check the "unlock" security attribute in the zip file's property before extracting it to avoid antivirus problem.

**Comment by bturne48** [comment]
Solved with fresh install and downloading System.Text.Json with NuGet
