### ISSUE TITLE
How to uninstall from TV

### ISSUE THREAD

**Issue by diegosugue** [Cathwyler/MagicRemoteService#35]
Hi! I have tried installing the app, but now I want to remove it from by TV, how can I do that?

**Comment by Cathwyler** [comment]
Hi.

You can remove it like any other web app. It depend on your webOS version. On 6.4.0 for exemple in the home page there a pen icon to manage, sort remove all the web app.
You can also desactivate or unisntall dev mode. It will remove the app at TV reboot.

Regards
