### ISSUE TITLE
Black screen at app launch

### ISSUE THREAD

**Issue by justmylukely** [Cathwyler/MagicRemoteService#4]
After the app is installed on the TV, it doesn't seem to show the HDMI4 input. It's just a black screen with a small white rectangle at the top? I've tried reinstalling the app and switching inputs.

**Comment by sanderszzzzzzz** [comment]
I have the same issue, black screen when installing the tv app. Only a white small box on the top left

**Comment by Cathwyler** [comment]
Can you tell me your TV model ? and the WebOS version ?

**Comment by quickstepp** [comment]
Hey, I have the same issue.

TV-Modell: 55SM8500PLA
WebOS: 4.9.7-17

**Comment by Cathwyler** [comment]
Hi,

I have only a webOS 6.x TV. The webOS is based on Chromium to render the entire OS. As you see [here](https://webostv.developer.lge.com/develop/specifications/web-api-and-web-engine) each webOS version is using is own Chromium version. The only way i am able to debug for older webOS version is to run the TV app on an older PC Chromium version.

The app was effectively throwing some exceptions on the older Chromium version, and i fixed them.
The last Chromium build version i was able to find is 52. This version is not far from webOS TV 4.x and Chromium 53. The TV app should now work on webOS TV 4.x ... and maybe 3.x.

Unfortunately, i don't have the possibility to test on a real older TV.
So, let me know if the app is now working on your TV. Hope it will work :).

Regards,

Cathwyler

**Comment by quickstepp** [comment]
For me, it's now working fine.

Thanks.

**Comment by justmylukely** [comment]
Sorry for not getting back with info sooner, but the fix worked for me too!

Thanks so much

**Comment by zaednasr** [comment]
hello my 43lm6300pla still has black screen. i am using the latest version. 
The remote works on my computer no problem
