### ISSUE TITLE
overlay experimental setting

### ISSUE THREAD

**Issue by TheoGal** [Cathwyler/MagicRemoteService#44]
Greetings and cheers on this great app. Got it all setup and working fine. I cant find any explanation of what the setting: overlay (experimental) in the TV tab of the windows app actually does. Any clues? thanks!

**Comment by Spottyfriend** [comment]
Was also wondering this?

**Comment by TheoGal** [comment]
Just found out: when enabled "magic remote service" doesnt appear as a seperate input in the list of inputs but rather you just select your hdmi port and it works
