### ISSUE TITLE
Error when opening the interface (VPN problem?)

### ISSUE THREAD

**Issue by Spottyfriend** [Cathwyler/MagicRemoteService#5]
Everything works fine I think (ie the remote works as a mouse as intended and all the buttons seem to work as I configured them), except that occasionally when trying to open MagicRemoteService's settings, I get this error. I have to reboot my PC, open MagicRemoteService, then click to install it on my TV again. Occasionally I get an error again and have to repeat.

(FYI I am using a VPN, but have enabled passthrough for MagicRemoteService. Maybe I need passthrough on something else?)

![image](https://github.com/Cathwyler/MagicRemoteService/assets/50644325/916cd655-9d4f-4b1d-8dde-cbe9d7895f46)

************** Exception Text **************
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at MagicRemoteService.MacAddressBox.set_Value(PhysicalAddress value)
   at MagicRemoteService.Setting.TVDataRefresh()
   at MagicRemoteService.Setting..ctor(Service mrs)
   at MagicRemoteService.Application.Setting(Object sender, EventArgs e)
   at System.Windows.Forms.NotifyIcon.OnDoubleClick(EventArgs e)
   at System.Windows.Forms.NotifyIcon.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.NotifyIcon.WndProc(Message& msg)
   at System.Windows.Forms.NotifyIcon.NotifyIconNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
MagicRemoteService
    Assembly Version: 1.2.0.0
    Win32 Version: 1.2.0.0
    CodeBase: file:///D:/MagicRemoteService_1.2.0.0/MagicRemoteService.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9172.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.ServiceProcess
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ServiceProcess/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.ServiceProcess.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

**Comment by Spottyfriend** [comment]
This version seems to work well regarding this. I don't get the bug and the WoL (on my other issue post) consistently works. Different problem now is that the auto-launch on startup no longer seems to work... I could probably make this work manually through Windows but the checkbox in the interface itself doesn't seem to work anymore

**Comment by Cathwyler** [comment]
The "Automatically launch at startup" option work through a Windows service.
This issue is probably because the Windows service is stopped at start. You can confirme it by checking the MagicRemoteService status in the Windows services list (Win+R and type services.msc).
When you have these kind of issue the best way is to save again the PC tab in MagicRemoteService settings. When saving the app reconfigure the MagicRemoteService Windows service and the firewall rule.

If you want to change the path of the executable file you need to stop the service or uncheck "Automatically launch at startup" option and save it. You will be able to move (or delete) the executable file. Once you did it you need to check the option (if not) and save again the PC tab. The Windows service will be configured with the new path.
